/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheoDoiRouteImport } from './routes/theo-doi'
import { Route as TongQuanRouteImport } from './routes/tong-quan'
import { Route as SanPhamIndexRouteImport } from './routes/san-pham.index'
import { Route as SanPhamIdRouteImport } from './routes/san-pham.$id'
import { Route as SanPhamMoiRouteImport } from './routes/san-pham.moi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoDoiRoute = TheoDoiRouteImport.update({
  id: '/theo-doi',
  path: '/theo-doi',
  getParentRoute: () => rootRouteImport,
} as any)
const TongQuanRoute = TongQuanRouteImport.update({
  id: '/tong-quan',
  path: '/tong-quan',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIndexRoute = SanPhamIndexRouteImport.update({
  id: '/san-pham/',
  path: '/san-pham/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIdRoute = SanPhamIdRouteImport.update({
  id: '/san-pham/$id',
  path: '/san-pham/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamMoiRoute = SanPhamMoiRouteImport.update({
  id: '/san-pham/moi',
  path: '/san-pham/moi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theo-doi': typeof TheoDoiRoute
  '/tong-quan': typeof TongQuanRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham/moi': typeof SanPhamMoiRoute
  '/san-pham/': typeof SanPhamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theo-doi': typeof TheoDoiRoute
  '/tong-quan': typeof TongQuanRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham/moi': typeof SanPhamMoiRoute
  '/san-pham': typeof SanPhamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theo-doi': typeof TheoDoiRoute
  '/tong-quan': typeof TongQuanRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham/moi': typeof SanPhamMoiRoute
  '/san-pham/': typeof SanPhamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/theo-doi'
    | '/tong-quan'
    | '/san-pham/$id'
    | '/san-pham/moi'
    | '/san-pham/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/theo-doi'
    | '/tong-quan'
    | '/san-pham/$id'
    | '/san-pham/moi'
    | '/san-pham'
  id:
    | '__root__'
    | '/'
    | '/theo-doi'
    | '/tong-quan'
    | '/san-pham/$id'
    | '/san-pham/moi'
    | '/san-pham/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TheoDoiRoute: typeof TheoDoiRoute
  TongQuanRoute: typeof TongQuanRoute
  SanPhamIdRoute: typeof SanPhamIdRoute
  SanPhamMoiRoute: typeof SanPhamMoiRoute
  SanPhamIndexRoute: typeof SanPhamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theo-doi': {
      id: '/theo-doi'
      path: '/theo-doi'
      fullPath: '/theo-doi'
      preLoaderRoute: typeof TheoDoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tong-quan': {
      id: '/tong-quan'
      path: '/tong-quan'
      fullPath: '/tong-quan'
      preLoaderRoute: typeof TongQuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/': {
      id: '/san-pham/'
      path: '/san-pham'
      fullPath: '/san-pham/'
      preLoaderRoute: typeof SanPhamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$id': {
      id: '/san-pham/$id'
      path: '/san-pham/$id'
      fullPath: '/san-pham/$id'
      preLoaderRoute: typeof SanPhamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/moi': {
      id: '/san-pham/moi'
      path: '/san-pham/moi'
      fullPath: '/san-pham/moi'
      preLoaderRoute: typeof SanPhamMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TheoDoiRoute: TheoDoiRoute,
  TongQuanRoute: TongQuanRoute,
  SanPhamIdRoute: SanPhamIdRoute,
  SanPhamMoiRoute: SanPhamMoiRoute,
  SanPhamIndexRoute: SanPhamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
