/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaiDatRouteImport } from './routes/cai-dat'
import { Route as HoSoRouteImport } from './routes/ho-so'
import { Route as MucDoSanSangRouteImport } from './routes/muc-do-san-sang'
import { Route as TheoDoiRouteImport } from './routes/theo-doi'
import { Route as TongQuanRouteImport } from './routes/tong-quan'
import { Route as NhaCungCapRouteImport } from './routes/nha-cung-cap'
import { Route as CongNhaCungCapRouteImport } from './routes/cong-nha-cung-cap'
import { Route as DppIndexRouteImport } from './routes/dpp.index'
import { Route as DppQrRouteImport } from './routes/dpp.qr'
import { Route as SanPhamIndexRouteImport } from './routes/san-pham.index'
import { Route as SanPhamIdRouteImport } from './routes/san-pham.$id'
import { Route as SanPhamMoiRouteImport } from './routes/san-pham.moi'
import { Route as DppCongKhaiIdRouteImport } from './routes/dpp.cong-khai.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaiDatRoute = CaiDatRouteImport.update({
  id: '/cai-dat',
  path: '/cai-dat',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoRoute = HoSoRouteImport.update({
  id: '/ho-so',
  path: '/ho-so',
  getParentRoute: () => rootRouteImport,
} as any)
const MucDoSanSangRoute = MucDoSanSangRouteImport.update({
  id: '/muc-do-san-sang',
  path: '/muc-do-san-sang',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoDoiRoute = TheoDoiRouteImport.update({
  id: '/theo-doi',
  path: '/theo-doi',
  getParentRoute: () => rootRouteImport,
} as any)
const TongQuanRoute = TongQuanRouteImport.update({
  id: '/tong-quan',
  path: '/tong-quan',
  getParentRoute: () => rootRouteImport,
} as any)
const NhaCungCapRoute = NhaCungCapRouteImport.update({
  id: '/nha-cung-cap',
  path: '/nha-cung-cap',
  getParentRoute: () => rootRouteImport,
} as any)
const CongNhaCungCapRoute = CongNhaCungCapRouteImport.update({
  id: '/cong-nha-cung-cap',
  path: '/cong-nha-cung-cap',
  getParentRoute: () => rootRouteImport,
} as any)
const DppIndexRoute = DppIndexRouteImport.update({
  id: '/dpp/',
  path: '/dpp/',
  getParentRoute: () => rootRouteImport,
} as any)
const DppQrRoute = DppQrRouteImport.update({
  id: '/dpp/qr',
  path: '/dpp/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIndexRoute = SanPhamIndexRouteImport.update({
  id: '/san-pham/',
  path: '/san-pham/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamIdRoute = SanPhamIdRouteImport.update({
  id: '/san-pham/$id',
  path: '/san-pham/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamMoiRoute = SanPhamMoiRouteImport.update({
  id: '/san-pham/moi',
  path: '/san-pham/moi',
  getParentRoute: () => rootRouteImport,
} as any)
const DppCongKhaiIdRoute = DppCongKhaiIdRouteImport.update({
  id: '/dpp/cong-khai/$id',
  path: '/dpp/cong-khai/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cai-dat': typeof CaiDatRoute
  '/ho-so': typeof HoSoRoute
  '/muc-do-san-sang': typeof MucDoSanSangRoute
  '/theo-doi': typeof TheoDoiRoute
  '/tong-quan': typeof TongQuanRoute
  '/nha-cung-cap': typeof NhaCungCapRoute
  '/cong-nha-cung-cap': typeof CongNhaCungCapRoute
  '/dpp/qr': typeof DppQrRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham/moi': typeof SanPhamMoiRoute
  '/dpp/': typeof DppIndexRoute
  '/san-pham/': typeof SanPhamIndexRoute
  '/dpp/cong-khai/$id': typeof DppCongKhaiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cai-dat': typeof CaiDatRoute
  '/ho-so': typeof HoSoRoute
  '/muc-do-san-sang': typeof MucDoSanSangRoute
  '/theo-doi': typeof TheoDoiRoute
  '/tong-quan': typeof TongQuanRoute
  '/nha-cung-cap': typeof NhaCungCapRoute
  '/cong-nha-cung-cap': typeof CongNhaCungCapRoute
  '/dpp/qr': typeof DppQrRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham/moi': typeof SanPhamMoiRoute
  '/dpp': typeof DppIndexRoute
  '/san-pham': typeof SanPhamIndexRoute
  '/dpp/cong-khai/$id': typeof DppCongKhaiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cai-dat': typeof CaiDatRoute
  '/ho-so': typeof HoSoRoute
  '/muc-do-san-sang': typeof MucDoSanSangRoute
  '/theo-doi': typeof TheoDoiRoute
  '/tong-quan': typeof TongQuanRoute
  '/nha-cung-cap': typeof NhaCungCapRoute
  '/cong-nha-cung-cap': typeof CongNhaCungCapRoute
  '/dpp/qr': typeof DppQrRoute
  '/san-pham/$id': typeof SanPhamIdRoute
  '/san-pham/moi': typeof SanPhamMoiRoute
  '/dpp/': typeof DppIndexRoute
  '/san-pham/': typeof SanPhamIndexRoute
  '/dpp/cong-khai/$id': typeof DppCongKhaiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cai-dat'
    | '/ho-so'
    | '/muc-do-san-sang'
    | '/theo-doi'
    | '/tong-quan'
    | '/nha-cung-cap'
    | '/cong-nha-cung-cap'
    | '/dpp/qr'
    | '/san-pham/$id'
    | '/san-pham/moi'
    | '/dpp/'
    | '/san-pham/'
    | '/dpp/cong-khai/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cai-dat'
    | '/ho-so'
    | '/muc-do-san-sang'
    | '/theo-doi'
    | '/tong-quan'
    | '/nha-cung-cap'
    | '/cong-nha-cung-cap'
    | '/dpp/qr'
    | '/san-pham/$id'
    | '/san-pham/moi'
    | '/dpp'
    | '/san-pham'
    | '/dpp/cong-khai/$id'
  id:
    | '__root__'
    | '/'
    | '/cai-dat'
    | '/ho-so'
    | '/muc-do-san-sang'
    | '/theo-doi'
    | '/tong-quan'
    | '/nha-cung-cap'
    | '/cong-nha-cung-cap'
    | '/dpp/qr'
    | '/san-pham/$id'
    | '/san-pham/moi'
    | '/dpp/'
    | '/san-pham/'
    | '/dpp/cong-khai/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaiDatRoute: typeof CaiDatRoute
  HoSoRoute: typeof HoSoRoute
  MucDoSanSangRoute: typeof MucDoSanSangRoute
  TheoDoiRoute: typeof TheoDoiRoute
  TongQuanRoute: typeof TongQuanRoute
  NhaCungCapRoute: typeof NhaCungCapRoute
  CongNhaCungCapRoute: typeof CongNhaCungCapRoute
  DppQrRoute: typeof DppQrRoute
  SanPhamIdRoute: typeof SanPhamIdRoute
  SanPhamMoiRoute: typeof SanPhamMoiRoute
  DppIndexRoute: typeof DppIndexRoute
  SanPhamIndexRoute: typeof SanPhamIndexRoute
  DppCongKhaiIdRoute: typeof DppCongKhaiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cai-dat': {
      id: '/cai-dat'
      path: '/cai-dat'
      fullPath: '/cai-dat'
      preLoaderRoute: typeof CaiDatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so': {
      id: '/ho-so'
      path: '/ho-so'
      fullPath: '/ho-so'
      preLoaderRoute: typeof HoSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muc-do-san-sang': {
      id: '/muc-do-san-sang'
      path: '/muc-do-san-sang'
      fullPath: '/muc-do-san-sang'
      preLoaderRoute: typeof MucDoSanSangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theo-doi': {
      id: '/theo-doi'
      path: '/theo-doi'
      fullPath: '/theo-doi'
      preLoaderRoute: typeof TheoDoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tong-quan': {
      id: '/tong-quan'
      path: '/tong-quan'
      fullPath: '/tong-quan'
      preLoaderRoute: typeof TongQuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nha-cung-cap': {
      id: '/nha-cung-cap'
      path: '/nha-cung-cap'
      fullPath: '/nha-cung-cap'
      preLoaderRoute: typeof NhaCungCapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-nha-cung-cap': {
      id: '/cong-nha-cung-cap'
      path: '/cong-nha-cung-cap'
      fullPath: '/cong-nha-cung-cap'
      preLoaderRoute: typeof CongNhaCungCapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpp/': {
      id: '/dpp/'
      path: '/dpp'
      fullPath: '/dpp/'
      preLoaderRoute: typeof DppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpp/qr': {
      id: '/dpp/qr'
      path: '/dpp/qr'
      fullPath: '/dpp/qr'
      preLoaderRoute: typeof DppQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/': {
      id: '/san-pham/'
      path: '/san-pham'
      fullPath: '/san-pham/'
      preLoaderRoute: typeof SanPhamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$id': {
      id: '/san-pham/$id'
      path: '/san-pham/$id'
      fullPath: '/san-pham/$id'
      preLoaderRoute: typeof SanPhamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/moi': {
      id: '/san-pham/moi'
      path: '/san-pham/moi'
      fullPath: '/san-pham/moi'
      preLoaderRoute: typeof SanPhamMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpp/cong-khai/$id': {
      id: '/dpp/cong-khai/$id'
      path: '/dpp/cong-khai/$id'
      fullPath: '/dpp/cong-khai/$id'
      preLoaderRoute: typeof DppCongKhaiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaiDatRoute: CaiDatRoute,
  HoSoRoute: HoSoRoute,
  MucDoSanSangRoute: MucDoSanSangRoute,
  TheoDoiRoute: TheoDoiRoute,
  TongQuanRoute: TongQuanRoute,
  NhaCungCapRoute: NhaCungCapRoute,
  CongNhaCungCapRoute: CongNhaCungCapRoute,
  DppQrRoute: DppQrRoute,
  SanPhamIdRoute: SanPhamIdRoute,
  SanPhamMoiRoute: SanPhamMoiRoute,
  DppIndexRoute: DppIndexRoute,
  SanPhamIndexRoute: SanPhamIndexRoute,
  DppCongKhaiIdRoute: DppCongKhaiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
